import { ApolloClient, InMemoryCache } from "@apollo/client";
import Head from "next/head";
import Link from "next/link";
import { GET_ALL_POSTS } from "../graphql/queries";
import React from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import emoji from "remark-emoji";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import rehypeHighlight from "rehype-highlight";

export default function Home({ posts }) {
	// console.log(posts);
	return (
		<div>
			<Head>
				<title>My blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				{/* CSS KATEX */}
				{/* <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css"></link> */}
			</Head>
			<h1>Welcome to Edu&apos;s Coding Blog</h1>
			<p>In this blog I will post my thoughts and experiences I encounter while searching for knowledge and working on projects. </p>
			<br />
			<h2>All posts</h2>
			<br />
			{posts.map((val, i) => {
				return (
					<Link key={i} href={val.attributes.urlSlug}>
						<a>
							<div className="card">
								<h3>
									<ReactMarkdown remarkPlugins={[remarkGfm, emoji, remarkMath]} rehypePlugins={[rehypeKatex, rehypeHighlight]}>
										{val.attributes.title}
									</ReactMarkdown>
								</h3>
								<ReactMarkdown remarkPlugins={[remarkGfm, emoji, remarkMath]} rehypePlugins={[rehypeKatex, rehypeHighlight]}>
									{val.attributes.description}
								</ReactMarkdown>
							</div>
						</a>
					</Link>
				);
			})}
		</div>
	);
}

export async function getStaticProps() {
	const client = new ApolloClient({
		uri: "https://cms.eperezme.com/graphql",
		cache: new InMemoryCache(),
	});

	const { data } = await client.query({
		query: GET_ALL_POSTS,
	});

	return {
		props: {
			posts: data.blogPosts.data,
		},
	};
}
